### ISSUE TITLE
'product.product' object has no attribute 'images'

### ISSUE THREAD

**Issue by laescudero** [ctmil/meli_oerp#10]
Al querer hacer un MELI POST arroja el siguiente error:

`File "/mnt/extra-addons/odoo-addons/meli_oerp/product_post.py", line 151, in product_post
    if (product.images):
AttributeError: 'product.product' object has no attribute 'images'`

**Comment by caebozzini** [comment]
Tengo exactamente el mismo problema.
Subí la imagen con el botón que está dentro del campo de MercadoLibre, le puse imagen al producto original, mismo error.

**Comment by caebozzini** [comment]
Comento por si le sirve a alguien, lo solucioné comentando todo lo relacionado a multi_images en product_post.py, postea bien a ML pero solo con dos imágenes.
