### ISSUE TITLE
Traduciendo a Odoo 10. Error

### ISSUE THREAD

**Issue by Yakito** [ctmil/meli_oerp#12]
Hola! Estoy intentando hacer funcionar el modulo para Odoo 10, pero luego de hacer algunas de las modificaciones en la manera en la que se llaman a los `fields` en Odoo 10, estoy trabado con un nuevo error al intentar instalarlo.

El error es:

```
ParseError: "Error mientras se validavan las restricciones

El campo `mercadolibre_secret_key` no existe

Error de contexto:
Vista `res.company.form.meli`
[view_id: 901, xml_id: no/disponible, model: res.company, parent_id: 111]
None" while parsing /odoo/custom/addons/meli_oerp-master/company_view.xml:13, near
<record model="ir.ui.view" id="view_company_page_mercadolibre">
```

Al parecer no puede encontrar el campo `mercadolibre_secret_key` aunque esta claramente definido en company.py. Si modifco el nombre no encuentra el siguiente, y así con todos. 

Alguien tiene idea de como puedo pasar este error para continuar con la migraciónd del módulo a Odoo 10? 

Muchas Gracias!

**Comment by morrillo** [comment]
Pregunta, como hiciste para actualizar el módulo? Por que no probas actualizando el módulo con los últimos contenidos del branch odoo10?
