### ISSUE TITLE
Error al instalar módulo en Odoo 9 Compose

### ISSUE THREAD

**Issue by lhazzi** [ctmil/meli_oerp#13]
Luego de clonar el módulo en la carpeta "custom_addons" y reiniciar el servidor, al acceder por el explorador tira el error clásico:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. 

 

Y en la consola tira lo siguiente:

odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
odoo_1  |     execute(self.server.app)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
odoo_1  |     application_iter = app(environ, start_response)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 250, in app
odoo_1  |     return self.app(e, s)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
odoo_1  |     return application_unproxied(environ, start_response)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
odoo_1  |     result = handler(environ, start_response)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1497, in __call__
odoo_1  |     return self.dispatch(environ, start_response)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1653, in dispatch
odoo_1  |     ir_http = request.registry['ir.http']
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 367, in registry
odoo_1  |     return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 355, in get
odoo_1  |     update_module)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 386, in new
odoo_1  |     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 336, in load_modules
odoo_1  |     force, status, report, loaded_modules, update_module)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 239, in load_marked_modules
odoo_1  |     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 123, in load_module_graph
odoo_1  |     load_openerp_module(package.name)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 331, in load_openerp_module
odoo_1  |     __import__('openerp.addons.' + module_name)
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 61, in load_module
odoo_1  |     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
odoo_1  |   File "/opt/odoo/custom-addons/meli_oerp/product.py", line 22, in <module>
odoo_1  |     from openerp import models, fields, api, _
odoo_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 60, in load_module
odoo_1  |     f, path, descr = imp.find_module(module_part, ad_paths)
odoo_1  | ImportError: No module named openerp

**Comment by morrillo** [comment]
de que branch estas tomando el módulo? yo lo acabo de instalar en la version 9 usando el branch master, y funcionó sin problemas.
Pregunta, probaste instalandolo sin docker?
