### ISSUE TITLE
Error Post Product

### ISSUE THREAD

**Issue by jbuitrago** [ctmil/meli_oerp#17]
[ERORES.docx](https://github.com/ctmil/meli_oerp/files/1588358/ERORES.docx)
Hola, tengon varios errores tratando de utilizar el modulo para Mexico (MLM) , me gustaria ver el log de errores pero no se donde esta. Gracias

**Comment by jbuitrago** [comment]
Hola, en el adjunto hay 3 problemas que encontré en el módulo:
1- Cuando hace el login aparece un error con el redirect_uri
2- Cuando hace la busqueda de productos no hay nada, no aparec ningún mensaje.

3- Cuando hago un post se queda pensando y no termina , luego me fijo en mercadolibre  y no crea ningún producto, solamente lo inserta en la tabla de productos 

Para que funcione en otro país tengo que modificar el código fuente,  podría ser un parámetro global.

Gracias espero su ayuda.

**Comment by ivanporras** [comment]
@jbuitrago el primer error que tienes es porque necesitas configurar una aplicacion en mercado libre y es necesario que tengas un dominio con SSL, al menos no logre configurarlo en mi localhost pero si en una VPS

**Comment by ivanporras** [comment]
@fabriciocosta quisiera contribuir en este proyecto y creo que estos errores son de configuracion que se pueden cerrar.
