### ISSUE TITLE
Odoo 8.0 da error al trata de publicar producto

### ISSUE THREAD

**Issue by guillermm** [ctmil/meli_oerp#19]
Hola, compañeros.-

Quería preguntarles como pueden ayudarme para resolver el siguiente error:
![pantallazo-2018-04-04 14-59-29](https://user-images.githubusercontent.com/18652795/38332066-ab7edb40-381a-11e8-97f2-c43e60c48adf.png)
Me sale al trata de publicar el producto.
En la versión 10 del branch odoo10mx me corre excelente todo funciona de maravilla, pero me urge correr este modulo en la versión 8.  Les agradezco mucho por la orientación.

**Comment by fabriciocosta** [comment]
Hola guilermm, estos errores son de mantenimiento de código en realidad, si quieres intentar de nuevo actualizando con el último commit debería estar funcionando nuevamente. Gracias

**Comment by guillermm** [comment]
Hola, @fabriciocosta gracias por responder. No se porque persiste el error, arroja la 114 en product_post, no entiendo que pasa ahí.

![pantallazo-2018-04-07 11-22-29](https://user-images.githubusercontent.com/18652795/38457509-cd23ccb8-3a56-11e8-8785-f7e53a55799a.png)

Saludos,
