### ISSUE TITLE
Que branch se puede utilizar en version 8 de odoo ?

### ISSUE THREAD

**Issue by guzzi235** [ctmil/meli_oerp#20]
Hola instale el branch master en odoo 8 pero no funciona correctamente, se puede instalar el branch 
odoo10 en 8 ?? alguien probo?. Desde y gracias.

**Comment by guillermm** [comment]
Hola, @guzzi235 no se puede, tiene muchos errores, han trabajado mucho sobre el master y ni te recomiendo que trabajes la versión "bikes", yo quería que la versión master por lo menos estuviese algo limpia para hacer un branch aparte y llamarlo 8.0 y dejarlo como modulo básico en versión 8 para el que lo necesite. Voy a estar pendiente. La versión que esta buena para mi punto de vista y la probé y se porta muy bien en este repositorio es la odoo10mx, no he probado la odoo11mx. En mi caso estoy pendiente de otro repositorio que le han hecho muchas modificaciones y esta más acorde a lo que estamos buscando es este https://github.com/laotraopcion/meli_oerp/tree/odoo10cl es una rama de Chile que promete mucho y el señor Carlos le ha puesto mucha dedicación y empeño con la colaboración del señor Fabricio de Argentina que ha trabajado en el código original junto a sus otros compañeros de odoo Argentina.

**Comment by fabriciocosta** [comment]
Bien amigos, les cuentos que estoy en plena reestructuración del código. Viendo los aportes de Carlos me estoy tomando el trabajo de reestructurar la rama https://github.com/ctmil/meli_oerp/tree/odoo10 para que pueda mezclarse con la de Carlos: https://github.com/laotraopcion/meli_oerp/tree/odoo10cl.   Es importante hacer esto con cuidado para no perder el trabajo de ambas ramas y a la vez dejar las funcionalidades bien identificadas, y sin conflictos. Ya he identificado todos los cambios y no son tantos, he empezado y en estos días ya lo tendré resuelto. Si realmente hay interés de seguir utilizando la **versión 8** he dejado en la rama https://github.com/ctmil/meli_oerp/tree/odoo8 esa versión para futuras consultas y mantenimiento. 

Personalmente pienso que resultará más fácil concentrar el desarrollo y el soporte en la versión 10. Luego la v11 y la v12 serán más fáciles de mantener.

Con respecto a la versión 8, la pondré al día para que sea funcional una vez que la versión 10 esté reorganizada y ya convertida en la rama MASTER.
