### ISSUE TITLE
Branch por versión y no por país, y wizard para soporte a diferentes países

### ISSUE THREAD

**Issue by grottas** [ctmil/meli_oerp#21]
Hola,

Este _issue_ para seguir la discusión que inició en #18 sobre llevar este módulo a que soporte varios países con un _Wizard_, y que se manejen branch por versiones de Odoo y no por países, con el ideal de centralizar el trabajo en este repositorio o en el de @laotraopcion de @celm1990.

cc @guillermm @joanodoo

**Comment by celm1990** [comment]
Estimado,

Me parece buena la iniciativa, expongo mis puntos de lo poco que he visto de mercado libre que se diferencia entre paises, y que considero no es mucho:
1.- **URL de conexion con la API**, se necesita pasar el ID del Site_id segun cada pais(MLC=chile, MLA=argentina, etc, etc) este para mi es el unico cambio en cuanto a la conexion.
2.- No tener el SDK de meli en el repo, se deberia usar la libreria disponible para instalacion via pip para no perder actualizaciones del propio desarrollador(https://github.com/mercadolibre/python-sdk)
3.- **Configuraciones en el ERP**, aca lo planteas como un asistente, pero en mi opinion personal lo veo como settings(res.config.settings con campos related hacia la compañia) y de esta manera no meter todas las configuraciones en la vista de formulario de la compañia.
Aca he visto campos que actualmente son configurables en la compañia y otros que no estan configurables pero deberia serlo, creo que seria mejor crear un documento  en Google Drive para ir dejando nota, xq de lo que he observador y me ha tocado cambiar o modificar tendria:
a) **Lista de Precios**, cuando hice el fork, se buscaba la lista de precios via codigo filtrando por el codigo de pais, deberia ser una configuracion
b) **Stock a usar en MELI**, en entornos multitiendas me he encontrado que no necesitan mostrar el stock de todos los almacenes sino de 1 o varios, por ello deberiamos agregar en el almacen que almacenes estan disponibles en MELI, esto actualmente esta en la rama de chile.
c) **Equipo de ventas**: Algo que le falta a la rama principal es terminar el flujo del pedido de venta en el ERP(validar el pedido, crear el picking, crear la factura, realizar el pago  y dejar la factura pagada), partiendo por validar el pedido de ventas, considero y me han pedido poder distinguir las ventas de MELI de las ventas normales del ERP a nivel de analisis, por ello la idea de asignar a todas las ventas provinientes de MELI un equipo de ventas especifico, y por ende se deberia crear un equipo de ventas y este ser configurable en la compañia.
4.- **Automatizacion en la creacion/Sincronizacion de Productos**, este deberia ser el enfoque del modulo, para facilitar la sincronizacion con meli, estaba por preguntarle a @fabriciocosta porque la razon de crear campos como: Precio en Meli(si puede ser el mismo campo de odoo y usar la Tarifa de venta para modificar el precio en base a descuentos, _punto a_), Stock en Meli(si puede ser el mismo campo de odoo filtrando stock en base al _punto b_. Aca tambien se me ocurre usar Category Predictor para facilitar este tema que es complicado de estar uno a uno configurando la categoria.

Para no alargar este comentario, creo que la primera cosa que debemos hacer es fusionar las ramas o decidir cual rama sera la base para los futuros cambios que hagamos.
Fusionar las ramas, como comente en el issue anterior, lo veo complicado xq estructuralmente yo he modificado los nombres de archivos y refactorizado mucho codigo(adaptandome mas a las guideslines de Odoo). En mi opinion personal la rama que mantengo de chile esta mas completa xq todos los puntos que mensiono aqui en este comentario ya estan resueltos y algunos de esos puntos en la rama principal no estan, asi que es un punto a favor. Pero les pediria que tomemos una decision lo mas pronto posible.
