### ISSUE TITLE
Compatibilidad con Uruguay?

### ISSUE THREAD

**Issue by pleirb** [ctmil/meli_oerp#23]
Veo que se han publicado ramas para varios países de latino américa, que tal Uruguay, es muy difícil hacer funcionar para este país?

**Comment by morrillo** [comment]
No es para nada dificil. Ya  esta funcionando en varios paises. Es cuestión de hacerlo y probarlo

**Comment by pleirb** [comment]
Me animaría a meter mano al código pero desconozco que puntos serian necesarios aplicar.

**Comment by morrillo** [comment]
sentite libre de hacerlo, si funciona y ves que es util, podes hacer un PR

**Comment by pleirb** [comment]
Nunca use Github, un PR es un Pull Requests? En mis tempos me revolvía con la programación pero debo ponerme en forma nuevamente y puedo llegar a hacer algo.

**Comment by morrillo** [comment]
es un pull request. Como dirian los australianos, we continue to live and learn

**Comment by pleirb** [comment]
Le doy al botón Publicar-actualizar en ML y me abre otra penstaña en el navegador con esto:
LOGGED WIT CODE: TG-5bca18ddd697550006e48d23-339859377 
ACCESS_TOKEN: APP_USR-2309131852370418-101913-b252d65f3d4b49756079a55e3fb1500c-339859377 
REFRESH_TOKEN: TG-5bca18dec0df9c0006ac6eac-339859377 
MercadoLibre for Odoo 8 - Moldeo Interactive  

Que significa? Voy a metrcadolibre a las publicaciones y no encuentro nada. Algo paso...

**Comment by pleirb** [comment]
En el LOG me sale esto también:

  File "/odoo/odoo-server/addons/product/models/product_uom.py", line 98, in _compute_quantity
    raise UserError(_('Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category!.') % (self.name, to_unit.name))
UserError: (u'\xa1La conversi\xf3n de la UdM m del producto a UdM por defecto Unit(s) no es posible debido a que no pertenecen a la misma categor\xeda!', '')
2018-10-19 17:51:38,125 1257 WARNING web.hfnet.uy odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.

**Comment by morrillo** [comment]
Dos cosas:
1) No es un error, es como se supone que debe funcionar. 
2) Tenes mal configurado el producto.
Un tema... esto de github es para postear los errores propios del módulo. No para hacer preguntas acerca del funcionamiento del mismo. Este módulo funciona, esta en producción en varios lugares y no plantean los problemas que estas planteando. Por favor, si tenes dudas con respecto al módulo, pregunta mediante el foro o sino contactanos directamente. Pero que quede bien claro, lo que publicamos es el módulo. No su documentación

**Comment by pleirb** [comment]
Gracias Morrillo, de verdad que no era mi intensión. Ya me queda claro. Intentare buscar información de uso en algún foro o por mis medios. En el caso de requerir ayuda, como puedo seguir en contacto contigo o alguien que este a cargo para solicitar servicio?

**Comment by morrillo** [comment]
El foro de Odoo Argentina es 
https://groups.google.com/forum/#!categories/odoo-argentina
si tengo una respuesta a tus dudas, las posteo ahí. No doy el mail debido a que la dirección de email es para clientes. Igual si una duda la tenes, en el foro la contestamos

**Comment by pleirb** [comment]
Nuevamente gracias !
