### ISSUE TITLE
No trae categorias odoo 11

### ISSUE THREAD

**Issue by trixocom** [ctmil/meli_oerp#27]
No arroja error alguno en consola, al pulsar "INICIAR IMPORTACION DE CATEGORIAS EN ML".
No hace nada, solo un get_meli_state exitoso. Pero no descarga nada. Esta check "Import all categories (recursiveness)".
Algun checkbox que falte?

**Comment by morrillo** [comment]
Hay algo que tenes mal configurado por lo visto. Pero no es error del módulo. Y github sirve para reportar issues, no para dar soporte a usuarios. Si tenes dudas sobre como funciona el módulo, manda un mail a odoo-argentina
