### ISSUE TITLE
El precio en Mercado Libre de Colombia no puede tener decimales.

### ISSUE THREAD

**Issue by JoanMarin** [ctmil/meli_oerp#31]
Estamos utilizando el modulo de la rama "odoo10" tuvimos un problema para publicar productos, esto era porque la API de Colombia restringe publicar con decimales, no sabemos si algún otro país tenga este problema, por lo que que le dimos solución a nuestro problema de la siguiente forma:
https://github.com/JoanMarin/meli_oerp/commit/967db3c6b094048cc1a892fcf1771a7079d1ea10
https://github.com/JoanMarin/meli_oerp/commit/49220b2070fe0ea3dcfca057ac0376dad15e40f0

Estos cambios solo cambian el procedimiento para Colombia, pero si hay otro país que tenga esta restricción, se puede complementar el código.

Queremos colaborar en este proyecto, desarrollamos nuestros cambios en nuestro repositorios y luego realizamos los pull request proponiendo nuestros cambios?, o proponen otra forma de colaborar?.

**Comment by Capriatto** [comment]
Implementado en odoo 11 para Colombia. "Works like a charm"

**Comment by ivanporras** [comment]
@JoanMarin Esto no se resuelve desde odoo? editando la presicion.

**Comment by fabriciocosta** [comment]
Cierro este issue ya que de hecho en la funcion set_meli_price existe ya esta mejora en la versiones 2020, 2021.
