### ISSUE TITLE
[12.0] Error al renovar credenciales

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#66]
Aunque el cron esté funcionando, nunca se llega a renovar el login, este es el msj de error que llega al mail:

Meli Odoo tried to refresh credentials for DB in the database DB but it failed. Here is the error message :
invalid_token

Debería renovar con el refresh token?

**Comment by fabriciocosta** [comment]
Esto lo cierro también que era un problema de permisos relacionado con el usuario OdooBot y la multicia. Si vuelve a surgir solo es necesario revisar los permisos de usuarios inactivos de sistema, aunque muchas veces pasa que desde MercadoLibre pueda haber algunos episodios de desconexiones forzadas debería estabilizarse en un par de días.
