### ISSUE TITLE
En compras con carrito el paid amount no tiene en cuenta el envío

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#67]
Si una compra fue hecha con carrito (múltiples productos) y tiene costo de envío, el mismo no se tiene en cuenta en el "Paid amount" y sólo suma el costo de los productos.

**Comment by fabriciocosta** [comment]
Voy a ir cerrando unos issues que ya vimos FedericioLaTorre, y dar de alta los issues más específicos. Acá abajo dejo un comentario por si quedan dudas.

En un carrito de compras tenes una, dos o mas ordenes de venta de ML, y un solo shipping, en la informacion de shipping se tiene la info detallada del carrito, alli puedes asegurarte que la Orden de Odoo esta bien dada de alta. Lo que si se deberia revisar es casos especiales, lo que se tiene en cuenta es el shipping_cost si es diferente de 0, caso en que se le cobra al cliente.
