### ISSUE TITLE
pdf2image no deja instalar

### ISSUE THREAD

**Issue by xinuxnt** [ctmil/meli_oerp#69]
Hola, intento instalar meli_oerp en odoo 14 sobre ubuntu 20.0 aunque pdf2image está instalado, sigue diciendo que falta el requerimiento y no permite instalar.

Imposible instalar el módulo "meli_oerp" porqué hay una dependencia externa no resuelta: Python library not installed: pdf2image

que puede ser?

**Comment by fabriciocosta** [comment]
En principio no exigimos una versión particular de pdf2image. Se debe reiniciar el servicio de Odoo, sino no reconoce el pdf2image. Por las dudas también ejecuta en el directorio de meli_oerp lo siguiente:

sudo pip3 install -r requirements.txt
