### ISSUE TITLE
Hi, Help me to resolve the next error in "post" method

### ISSUE THREAD

**Issue by Richardgh83** [ctmil/meli_oerp#7]
File "/home/openerp/instancias/estable/8.0/modules/meli_oerp/product_post.py", line 84, in product_post
    product.product_post()
AttributeError: 'product.product' object has no attribute 'product_meli_post'

**Comment by leandrodalbo** [comment]
hola queria saber si es correcto lo que hice?

Cree un metodo product_meli_post en la clase product_product en el modulo product.py con lo que se encuentra dentro de este for. Este metodo es llamado desde el metodo product_post en la clase product_post en el modulo product_ post.

Desde ya muchas gracias.

**Comment by leandrodalbo** [comment]
hi I wanted to know if it is ok.

I created a method product_meli_post in the class product_product in the module product.py with the code that is inside de for in the commit. This method is called from the method produc_post in the class product_post in the module product_post.

THANKS FOR ALL.

**Comment by Richardgh83** [comment]
Que tal, Leandro sobre tu pregunta no se como para que creaste el metodo, lo que si se es que el modulo funciona mesclando la los 2 forks https://github.com/ctmil/meli_oerp y  https://github.com/nh-autopiezas/meli_oerp
