### ISSUE TITLE
Al importa m anual productos o al actualizar manual productos no actualiza precios.

### ISSUE THREAD

**Issue by pronexo-argentina** [ctmil/meli_oerp#78]
Versión: 14.0.21.81
Al importar manual productos o al actualizar manual productos **no actualiza precios**. El problema está en la función **product_meli_get_product** en el archivo **meli_oerp/models/product.py**

El error que dice el log de odoo 

name 'config' is not defined 
Traceback (most recent call last):
  File "/addons/meli_oerp/models/product.py", line 1083, in product_meli_get_product
    product._meli_set_product_price( product_template, rjson['price'], force_variant=force_price_for_variant, config=config )
NameError: name 'config' is not defined

De momento he resuelto el problema cambiando:
def product_meli_get_product( self, meli_id=None):
 por
def product_meli_get_product( self, meli_id=None **,  config=None** ):

**Comment by fabriciocosta** [comment]
Muy bien, estos errores suelen corregirse rápido, la próxima, puedes hacer un Pull Request.
La funcion sería hoy:

def _meli_set_product_price( self, product_template, meli_price, force_variant=False, config=None ):

Gracias!
