### ISSUE TITLE
Posibilidad de no importar código de barras

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#79]
Si el código de barras en ML ya existe en odoo, no se pueden importar los productos.

**Comment by fabriciocosta** [comment]
Bueno se agrego código específico para que incluso chequee si no está repetido el código de barra antes de intentar setearlo.
Lo cierro.

Agregaría igualmente como enhancement lo siguiente, aunque lo hablamos con Ignacio también, quisiera no tocarlo demasiado, podemos armar un branch para testearlo:
Agregar un campo especifico para chequear si existe el barcode, y tambíén para importar el barcode o publicarlo en ML. Son 3 campos que espero tener un poco más claro cuando agregarlos para no romper la dependencia.
