### ISSUE TITLE
[12.0] No agrega el costo a la linea de envío

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#82]

**Comment by fabriciocosta** [comment]
Se podria chequear que esto esta ok? La configuracion del total deberia estar en "Paid Amount" en la configuracion.

**Comment by FedericoLaTorre** [comment]
Está en paid amount, pero en la línea del envío no carga el precio, ni siquiera pone en 1 la cantidad. Pero en la pestaña de ML si figuran todos los costos.

**Comment by FedericoLaTorre** [comment]
Funciona bien en las últimas versiones.
