### ISSUE TITLE
no actualiza precio de productos  en la version 13

### ISSUE THREAD

**Issue by albertonajerambq** [ctmil/meli_oerp#83]
No me actualiza el precio de odoo a mercado libre en  la version 13

**Comment by javialon26** [comment]
Hola, me pasa lo mismo con ciertos productos (algunos funcionan bien), no pude encontrar cual es la diferencia entre esos productos. No actualiza el precio en ML cuando uso la funcion de publicar desde la vista de template de producto y tampoco lo hace con el cron job. Por otro lado funciona manualmente desde la vista de variante.

**Comment by fabriciocosta** [comment]
Deben activar el cron de meli post price, es un nuevo cron ahora especifico para los precios. Por otro lado en Notificaciones veran agrupando por Topic > Resource el log de errores que generaron algunos posts (bids: producto con ventas, no se puede modificar precios, o alguna incongruencia con los ids de variantes por ejemplo). Saludos, cierro el ticket.
