### ISSUE TITLE
Error actualizando ORDEN <<< ('Longitud invalida para "DNI"', None) 

### ISSUE THREAD

**Issue by nahe-consulting-group** [ctmil/meli_oerp#85]
No voy a publicar datos completos de clientes por un tema de responsabilidad en la seguridad de los datos pero: 
Leyendo los logs veo que en odoo 13 falla en crear las ordenes de clientes que tengan CUIT andan bien si es DNI 
odoo.addons.meli_oerp.models.orders: ('Longitud invalida para "DNI"', None)
  File "/opt/odoo13/odoo/repositorios/moldeo-meli_oerp/meli_oerp/models/orders.py", line 1468, in orders_query_iterate
  File "/opt/odoo13/odoo/repositorios/moldeo-meli_oerp/meli_oerp/models/orders.py", line 982, in orders_update_order_json

**Comment by fabriciocosta** [comment]
Versión de Odoo y de la localización implementada ayudarían a saber porque sucede.

**Comment by fabriciocosta** [comment]
Version 140 resuelve, porque define el tipo de documento correctamente en la localizacion l10n_latam para Argentina.
